spring:
  application:
    name: ms-registry-server
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7071

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
