server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms-estudiante
              uri: lb://ms-estudiante
              predicates:
                - Path=/estudiantes/**

            - id: ms-curso
              uri: lb://ms-curso
              predicates:
                - Path=/cursos/**

            - id: ms-matricula
              uri: lb://ms-matricula
              predicates:
                - Path=/matriculas/**

              # Si tu servicio real no expone /categoria/...:
              # filters:
              #   - StripPrefix=1