server:
  port: 8090

spring:
  application:
    name: ms-registry-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 1000